# This values.yaml file provides default configuration for Turing Helm chart. 
# It is also currently used to generate README.md using helm-docs
# https://github.com/norwoodj/helm-docs

turing:
  image:
    # -- Docker registry for Turing API image. User is required to override
    # the registry for now as there is no publicly available Turing image
    registry: docker.io/
    # -- Docker image repository for Turing API
    repository: turing
    # -- Docker image tag for Turing API
    tag: latest
  # -- Resources requests and limits for Turing API. This should be set 
  # according to your cluster capacity and service level objectives.
  # Reference: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  resources: {}
  livenessProbe:
    # -- HTTP path for liveness check
    path: "/v1/internal/live"
  readinessProbe:
    # -- HTTP path for readiness check
    path: "/v1/internal/ready"
  service:
    # -- Turing API Kubernetes service port number
    externalPort: 8080
    # -- Turing API container port number
    internalPort: 8080
  ingress:
    enabled: false
  config: {}

dbMigrations:
  image:
    # -- Docker tag for golang-migrate Docker image https://hub.docker.com/r/migrate/migrate
    tag: v4.7.1

swaggerUi:
  # -- Docker tag for Swagger UI https://hub.docker.com/r/swaggerapi/swagger-ui
  image:
    tag: v3.24.3
  # -- Host for the Swagger UI
  apiHost: "127.0.0.1"
  # -- Base URL path to serve the Swagger UI
  basePath: "/v1"
  service:
    # -- Swagger UI container port number
    internalPort: 8081
    # -- Swagger UI Kubernetes service port number
    externalPort: 8080

postgresql:
  # -- Resources requests and limits for Turing database. This should be set 
  # according to your cluster capacity and service level objectives.
  # Reference: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  resources: {}
  persistence:
    # -- Persist Postgresql data in a Persistent Volume Claim 
    enabled: true
  # -- Database name for Turing Postgresql database
  postgresqlDatabase: turing
  # -- Username for Turing Postgresql database
  postgresqlUsername: turing
  # -- Password for Turing Postgresql database (required)
  postgresqlPassword:
