dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 10.16.2
  - name: vault
    repository: https://helm.releases.hashicorp.com
    version: 0.16.1
    condition: vault.enabled