ARG TURING_API_IMAGE

# Build optimized static turing-ui bundle
FROM node:14 as ui-builder

ARG REACT_APP_ENVIRONMENT
ARG REACT_APP_TURING_API="/v1"
ARG REACT_APP_MERLIN_API
ARG REACT_APP_MLP_API
ARG REACT_APP_OAUTH_CLIENT_ID
ARG REACT_APP_SENTRY_DSN
ARG REACT_APP_USER_DOCS_URL
ARG REACT_APP_RESULT_LOG_PROTO_URL
ARG REACT_APP_PRIVATE_DOCKER_REGISTRIES
ARG REACT_APP_DEFAULT_DOCKER_REGISTRY
ARG REACT_APP_MAX_ALLOWED_REPLICA

RUN mkdir -p /opt/turing_ui
COPY ./ui /opt/turing_ui
WORKDIR /opt/turing_ui

ENV NODE_OPTIONS "--max_old_space_size=2048"

RUN yarn install --network-concurrency 1
RUN yarn build

FROM ${TURING_API_IMAGE}

ENV TURINGUICONFIG_SERVINGDIRECTORY "./turing-ui"

COPY --from=ui-builder /opt/turing_ui/build ${TURINGUICONFIG_SERVINGDIRECTORY}/
