ARG TURING_API_IMAGE
FROM ${TURING_API_IMAGE}

ARG TURING_USER=${TURING_USER:-turing}
ARG TURING_USER_GROUP=${TURING_USER_GROUP:-app}

USER root
RUN apk add --no-cache bash
USER ${TURING_USER}

ARG TURING_UI_DIST_PATH=ui/build
ARG SWAGGER_UI_DIST_PATH=api/api/swagger-ui-dist

ENV TURINGUICONFIG_SERVINGDIRECTORY "./turing-ui"
ENV OPENAPICONFIG_SWAGGERUICONFIG_SERVINGDIRECTORY "./swagger-ui"

COPY --chown=${TURING_USER}:${TURING_USER_GROUP} ${TURING_UI_DIST_PATH} ${TURINGUICONFIG_SERVINGDIRECTORY}/
COPY --chown=${TURING_USER}:${TURING_USER_GROUP} ${SWAGGER_UI_DIST_PATH} ${OPENAPICONFIG_SWAGGERUICONFIG_SERVINGDIRECTORY}/

COPY ./docker-entrypoint.sh ./

ENV TURING_UI_DIST_DIR ${TURINGUICONFIG_SERVINGDIRECTORY}

ENTRYPOINT ["./docker-entrypoint.sh"]
