apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "turing.fullname" .}}-svc-secret
data:
  vault_token: {{ .Values.turing.config.vault.token | b64enc }}
  turing_encryption_key: {{ .Values.turing.config.encryption.key | b64enc }}
  mlp_encryption_key: {{ .Values.turing.config.mlp.encryption.key | b64enc }}
  {{- if .Values.turing.config.alert.enabled }}
  gitlab_token: {{ .Values.turing.config.alert.gitlabToken | b64enc }}
  {{- end }}
