apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "turing.fullname" .}}-api-config
stringData:
  config.yaml: |
    {{- toYaml .Values.turing.config | nindent 4 -}}
