apiVersion: v1
kind: Service
metadata:
  name: {{ template "turing.fullname" .}}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "turing.fullname" .}}
    chart: {{ template "turing.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{ if .Values.turing.labels -}}
{{ toYaml .Values.turing.labels | indent 4 -}}
{{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.turing.service.externalPort }}
      targetPort: {{ .Values.turing.service.internalPort }}
      protocol: TCP
  selector:
    app: {{ template "turing.fullname" .}}
    release: {{ .Release.Name }}
