mlp:
  image:
    registry: ghcr.io
    repository: gojek/mlp
    # Value will be set at install time using helm --set command
    tag:
  environment: dev
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 128Mi
  encryption:
    key: password

postgresql:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
  persistence:
    enabled: false
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
  replication:
    enabled: false
