// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import (
	batchcontroller "github.com/gojek/turing/api/turing/batch/controller"
	mock "github.com/stretchr/testify/mock"
)

// EnsemblingController is an autogenerated mock type for the EnsemblingController type
type EnsemblingController struct {
	mock.Mock
}

// Create provides a mock function with given fields: request
func (_m *EnsemblingController) Create(request *batchcontroller.CreateEnsemblingJobRequest) error {
	ret := _m.Called(request)

	var r0 error
	if rf, ok := ret.Get(0).(func(*batchcontroller.CreateEnsemblingJobRequest) error); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
