apiVersion: v1
kind: Secret
metadata:
  name: {{ template "merlin.fullname" . }}-postgresql-mlflow-init-scripts
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "merlin.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    helm.sh/chart: {{ include "merlin.chart" . }}
    app.kubernetes.io/name: {{ include "merlin.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  init_mlflow_backend_store.sh: |-
    #!/bin/sh
    set -e
    echo "Create DATABASE {{ .Values.mlflow.postgresql.auth.database }} with OWNER {{ .Values.mlflow.postgresql.auth.username }}:"
    psql -v ON_ERROR_STOP=1 --username "postgres" <<-EOSQL
      CREATE USER {{ .Values.mlflow.postgresql.auth.username }} WITH PASSWORD '{{ .Values.mlflow.postgresql.auth.password }}';
      CREATE DATABASE {{ .Values.mlflow.postgresql.auth.database }};
      GRANT ALL PRIVILEGES ON DATABASE {{ .Values.mlflow.postgresql.auth.database }} TO {{ .Values.mlflow.postgresql.auth.username }};
    EOSQL
    echo "Done."
