apiVersion: v1
kind: Secret
metadata:
  name: {{ template "merlin.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "merlin.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    helm.sh/chart: {{ include "merlin.chart" . }}
    app.kubernetes.io/name: {{ include "merlin.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  mlp-encryption-key: {{ include "merlin.mlp.encryption.key" . | b64enc | quote }}
  {{- if .Values.vault.enabled }}
  vault-address: {{ include "merlin.vault.address" . | b64enc | quote }}
  vault-token: {{ default "root" .Values.vault.server.dev.devRootToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.alert.enabled }}
  gitlab-token: {{ .Values.gitlab.token | default "" | b64enc | quote }}
  {{- end }}