global:
  scrape_interval:     5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: turing_custom_metrics
    # Collect from 2 replicas
    dns_sd_configs:
    - names:
      - 'tasks.turing-app'
      type: 'A'
      port: 8080
    # Add labels
    relabel_configs:
    - source_labels:
      - status
      target_label: namespace
      regex: (.*)
      replacement: 'test_namespace'
      action: replace
    - source_labels:
      - status
      target_label: service
      regex: (.*)
      replacement: 'turing_router'
      action: replace
