{{- if .Values.turing.clusterConfig.useInClusterConfig -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "turing.serviceAccount.name" . }}-role-binding
  labels:
    app: {{ template "turing.fullname" . }}
    chart: {{ template "turing.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.turing.labels }}
{{ toYaml .Values.turing.labels | indent 4 -}}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "turing.serviceAccount.name" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ template "turing.serviceAccount.name" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
