apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "turing.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "turing.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.turing.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "turing.fullname" . }}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ template "turing.fullname" . }}
        release: {{ .Release.Name }}
{{- if .Values.turing.labels }}
{{ toYaml .Values.turing.labels | indent 8 -}}
{{- end }}
    spec:
      {{- if .Values.turing.clusterConfig.useInClusterConfig }}
      serviceAccountName: {{ template "turing.serviceAccount.name" . }}
      {{- end }}
      {{- with (include "turing.initContainers" . | fromYaml) }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: api
        image: {{ template "turing.image" . }}
        imagePullPolicy: {{ .Values.turing.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.turing.service.internalPort }}
        livenessProbe:
          httpGet:
            path: {{ .Values.turing.livenessProbe.path }}
            port: {{ .Values.turing.service.internalPort }}
            scheme: HTTP
          initialDelaySeconds: {{ default "60" .Values.turing.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ default "10" .Values.turing.livenessProbe.periodSeconds }}
          successThreshold: {{ default "1" .Values.turing.livenessProbe.successThreshold }}
          timeoutSeconds: {{ default "5" .Values.turing.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.turing.readinessProbe.path }}
            port: {{ .Values.turing.service.internalPort }}
            scheme: HTTP
          initialDelaySeconds: {{ default "60" .Values.turing.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ default "10" .Values.turing.readinessProbe.periodSeconds }}
          successThreshold: {{ default "1" .Values.turing.readinessProbe.successThreshold }}
          timeoutSeconds: {{ default "5" .Values.turing.readinessProbe.timeoutSeconds }}
        resources:
          {{- toYaml .Values.turing.resources | nindent 12 }}
        args:
        - -config
        - /etc/turing/config.yaml
        {{- if .Values.turing.uiConfig }}
        - -ui-config
        - /etc/turing/ui.config.json
        {{- end }}
        {{- with .Values.turing.extraArgs }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        env:
        {{- with .Values.turing.extraEnvs }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /etc/turing
        - name: plugins-volume
          mountPath: {{ include "turing.plugins.directory" . }}
        {{- if .Values.turing.openApiSpecOverrides }}
        - name: openapi
          mountPath: /etc/openapi
        {{- end }}
        {{- with .Values.turing.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.turing.extraContainers }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      volumes:
      - name: config 
        secret:
          secretName: {{ template "turing.fullname" . }}-api-config
      - name: plugins-volume
        emptyDir: {}
      {{- if .Values.turing.openApiSpecOverrides }}
      - name: openapi 
        configMap:
          name: {{ template "turing.fullname" . }}-openapi
      {{- end }}
      {{- with .Values.turing.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}

{{- if (not .Values.turing.nodeSelectorDisabled) }}
{{- if .Values.turing.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.turing.nodeSelector | indent 8 }}
{{ end -}}
{{ end -}}
