apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "turing.fullname" . }}-api-config
  labels:
    app: {{ template "turing.fullname" . }}
    chart: {{ template "turing.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.turing.labels }}
{{ toYaml .Values.turing.labels | indent 4 -}}
{{- end }}
stringData:
  config.yaml: |
    {{- include "turing.config" . | nindent 4 -}}
  {{- if .Values.turing.uiConfig }}
  ui.config.json: |
    {{- include "turing.ui.config" . | nindent 4 -}}
  {{- end }}
