apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "turing.fullname" . }}-api-config
  labels:
{{ include "turing.labels" . | indent 4 }}
stringData:
  config.yaml: |
    {{- include "turing.config" . | nindent 4 -}}
  {{- if .Values.turing.uiConfig }}
  ui.config.json: |
    {{- include "turing.ui.config" . | nindent 4 -}}
  {{- end }}
