apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "turing.fullname" .}}-api-config
stringData:
  config.yaml: |
    {{- toYaml .Values.turing.config | nindent 4 -}}
  {{- if .Values.turing.uiConfig }}
  ui.config.json: |
    {{- toJson .Values.turing.uiConfig | nindent 4 -}}
  {{- end }}
