{{- if .Values.turing.clusterConfig.useInClusterConfig -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "turing.serviceAccount.name" . }}
  labels:
    app: {{ template "turing.fullname" . }}
    chart: {{ template "turing.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.turing.labels }}
{{ toYaml .Values.turing.labels | indent 4 -}}
{{- end }}
{{- end -}}
