{{- if .Values.turing.clusterConfig.useInClusterConfig -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "turing.serviceAccount.name" . }}
  labels:
{{ include "turing.labels" . | indent 4 }}
{{- end -}}
