apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "turing-init.serviceAccountName" . }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - pods/exec
  - pods/portforward
  - namespaces
  - configmaps
  - secrets
  - serviceaccounts
  - endpoints
  - persistentvolumeclaims
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - daemonsets
  verbs:
  - "*"
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - "*"
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - "*"
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  - envoyfilters
  - gateways
  - destinationrules
  verbs:
  - "*"
- apiGroups:
  - security.istio.io
  resources:
  - peerauthentications
  verbs:
  - "*"
- apiGroups:
  - install.istio.io
  resources:
  - istiooperators
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - "*"
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - "*"
- apiGroups:
  - caching.internal.knative.dev
  resources:
  - images
  verbs:
  - "*"
