apiVersion: v1
kind: ConfigMap
metadata:
  name: config-features
  namespace: knative-serving
  labels:
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: devel
  annotations:
    knative.dev/example-checksum: "4d5feafc"
data:
  kubernetes.podspec-volumes-emptydir: "enabled"
  kubernetes.podspec-init-containers: "enabled"