name: pyfunc-ensembler-job
dependencies:
  - python=3.8
  - pip=21.0.1
  - pip:
      - -r file:requirements.txt
      - --extra-index-url=https://test.pypi.org/simple
      - --trusted-host=test.pypi.org
