version: '3.1'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui:v3.52.0
    ports:
      - 8081:5555
    volumes:
      - ../api:/app:ro
    environment:
      - PORT=5555
      - LAYOUT=BaseLayout
      - SWAGGER_JSON=/app/openapi.yaml
