version: '3.1'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318

  pyroscope:
    image: grafana/pyroscope:latest
    ports:
      - 4040:4040
