// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import (
	imagebuilder "github.com/gojek/turing/api/turing/imagebuilder"
	mock "github.com/stretchr/testify/mock"
)

// ImageBuilder is an autogenerated mock type for the ImageBuilder type
type ImageBuilder struct {
	mock.Mock
}

// BuildImage provides a mock function with given fields: request
func (_m *ImageBuilder) BuildImage(request imagebuilder.BuildImageRequest) (string, error) {
	ret := _m.Called(request)

	var r0 string
	if rf, ok := ret.Get(0).(func(imagebuilder.BuildImageRequest) string); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(imagebuilder.BuildImageRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
