apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mlp.fullname" . }}-db-migrations
data:
  {{- $root := . }}
  {{ range $path, $_ := .Files.Glob "db-migrations/*.sql" }}
{{ base $path | indent 2  }}: |-
{{ $root.Files.Get $path | indent 4}}
  {{- end }}
