apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mlp.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "mlp.name" . }}
    chart: {{ include "mlp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "mlp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  encryption-key: {{ include "mlp.encryption.key" . | b64enc | quote }}
  {{- if .Values.gitlab.enabled }}
  gitlab-client-id: {{ .Values.gitlab.clientId | default "" | b64enc | quote }}
  gitlab-client-secret: {{ .Values.gitlab.clientSecret | default "" | b64enc | quote }}
  {{- end }}