openapi: 3.0.3
info:
  title: Common types of Turing schemas
  version: 0.0.1

paths:

components:
  schemas:
    Id:
      type: "integer"
      format: "int32"

    FieldSource:
      type: "string"
      enum:
        - "header"
        - "payload"

    pagination.Paging:
      type: "object"
      properties:
        total:
          type: "integer"
          format: "int32"
          description: "Total number of results matching the query criteria"
        page:
          type: "integer"
          format: "int32"
          description: "Number of the current page"
        pages:
          type: "integer"
          format: "int32"
          description: "Total number of pages"
