openapi: 3.0.3
info:
  title: Endpoints and schemas of Turing ensembler images
  version: 0.0.1

.tags: &tags
  - "Ensembler Images"

.id: &id
  type: "integer"
  format: "int32"

paths:
  "/projects/{project_id}/ensemblers/{ensembler_id}/images":
    get:
      tags: *tags
      operationId: "ListEnsemblerImages"
      summary: Returns a list of ensembler images that belong to the ensembler
      parameters:
        - in: path
          name: project_id
          schema:
            <<: *id
          required: true
        - in: path
          name: ensembler_id
          schema:
            <<: *id
          required: true
        - in: query
          name: runner_type
          schema:
            "$ref": "#/components/schemas/EnsemblerImageRunnerType"
          required: false
      responses:
        "200":
          description: A JSON object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EnsemblerImages"
        "400":
          description: Invalid request body
        "404":
          description: Ensembler not found
        "500":
          description: Unable to list ensembler images
    put:
      tags: *tags
      operationId: "CreateEnsemblerImage"
      summary: Creates a new ensembler image
      parameters:
        - in: path
          name: project_id
          schema:
            <<: *id
          required: true
        - in: path
          name: ensembler_id
          schema:
            <<: *id
          required: true
      requestBody:
        description: A JSON object containing information about the ensembler
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BuildEnsemblerImageRequest"
      responses:
        "202":
          description: Accepted
        "400":
          description: Invalid request body
        "404":
          description: Ensembler not found
        "500":
          description: Unable to build ensembler image

components:
  schemas:
    EnsemblerId:
      $ref: "./common.yaml#/components/schemas/IdObject"

    EnsemblerImages:
      type: array
      items:
        $ref: "#/components/schemas/EnsemblerImage"

    EnsemblerImage:
      type: object
      properties:
        project_id:
          type: integer
          format: int32
        ensembler_id:
          type: integer
          format: int32
        runner_type:
          "$ref": "#/components/schemas/EnsemblerImageRunnerType"
        image_ref:
          type: string
        exists:
          type: boolean
        image_building_job_status:
          "$ref": "#/components/schemas/ImageBuildingJobStatus"

    EnsemblerImageRunnerType:
      type: string
      nullable: true
      enum:
        - job
        - service

    ImageBuildingJobStatus:
      type: object
      properties:
        state:
          "$ref": "#/components/schemas/ImageBuildingJobState"
        message:
          type: string
    ImageBuildingJobState:
      type: string
      enum:
        - active
        - succeeded
        - failed
        - unknown

    BuildEnsemblerImageRequest:
      type: object
      properties:
        runner_type:
          "$ref": "#/components/schemas/EnsemblerImageRunnerType"
      required:
        - runner_type
