openapi: 3.0.3
info:
  title: Endpoints and schemas of Turing ensemblers
  version: 0.0.1

.tags: &tags
  - "Ensembler"

paths:
  "/projects/{project_id}/ensemblers":
    get:
      tags: *tags
      operationId: "ListEnsemblers"
      summary: Returns a list of ensemblers that belong to the project
      parameters:
        - in: path
          name: project_id
          schema:
            $ref: "#/components/schemas/Id"
          required: true
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: page_size
          schema:
            type: integer
            default: 10
        - in: query
          name: type
          schema:
            $ref: "#/components/schemas/EnsemblerType"
      responses:
        "200":
          description: A JSON object, that represents paginated results response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EnsemblersPaginatedResults"
    post:
      tags: *tags
      operationId: "CreateEnsembler"
      summary: Saves a user-defined ensembler into the project
      parameters:
        - in: path
          name: project_id
          schema:
            $ref: "#/components/schemas/Id"
          required: true
      requestBody:
        description: A JSON object containing information about the ensembler
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Ensembler"
      responses:
        "201":
          description: A JSON representation of a successfully saved ensembler
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ensembler"

  "/projects/{project_id}/ensemblers/{ensembler_id}":
    get:
      tags: *tags
      operationId: "GetEnsemblerDetails"
      summary: Returns Ensembler's details by its ID
      parameters:
        - in: path
          name: project_id
          schema:
            $ref: "#/components/schemas/Id"
          required: true
        - in: path
          name: ensembler_id
          schema:
            $ref: "#/components/schemas/Id"
          required: true
      responses:
        "200":
          description: A JSON object representing an instance of the specific type of Ensembler
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ensembler"
    put:
      tags: *tags
      operationId: "UpdateEnsembler"
      summary: Updates existing Ensembler with the data provided in the payload
      parameters:
        - in: path
          name: project_id
          schema:
            $ref: "#/components/schemas/Id"
          required: true
        - in: path
          name: ensembler_id
          schema:
            $ref: "#/components/schemas/Id"
          required: true
      requestBody:
        description: A JSON object, representing an update to the ensembler
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Ensembler"
      responses:
        "200":
          description: A JSON object representing an instance of updated Ensembler
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ensembler"

components:
  schemas:
    Id:
      $ref: "common.yaml#/components/schemas/Id"

    EnsemblerType:
      type: "string"
      enum:
        - pyfunc

    Ensembler:
      type: object
      oneOf:
        - $ref: "#/components/schemas/PyFuncEnsembler"
      discriminator:
        propertyName: "type"
        mapping:
          pyfunc: '#/components/schemas/PyFuncEnsembler'

    GenericEnsembler:
      required:
        - "type"
      properties:
        id:
          $ref: "common.yaml#/components/schemas/Id"
        project_id:
          $ref: "common.yaml#/components/schemas/Id"
        type:
          $ref: "#/components/schemas/EnsemblerType"
        name:
          type: "string"
          minLength: 3
          maxLength: 20
        created_at:
          type: "string"
          format: "date-time"
        updated_at:
          type: "string"
          format: "date-time"

    PyFuncEnsembler:
      allOf:
        - $ref: "#/components/schemas/GenericEnsembler"
        - type: "object"
          properties:
            mlflow_url:
              type: "string"
              format: "uri"
            mlflow_experiment_id:
              $ref: "common.yaml#/components/schemas/Id"
            mlflow_run_id:
              type: "string"
            artifact_uri:
              type: "string"
              format: "uri"

    EnsemblersPaginatedResults:
      allOf:
        - type: object
          properties:
            paging:
              $ref: "common.yaml#/components/schemas/pagination.Paging"
        - type: object
          properties:
            results:
              type: array
              items:
                $ref: "#/components/schemas/GenericEnsembler"
