// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	errors "github.com/caraml-dev/turing/engines/router/missionctl/errors"
	fiber "github.com/gojek/fiber"

	mock "github.com/stretchr/testify/mock"

	upiv1 "github.com/caraml-dev/universal-prediction-interface/gen/go/grpc/caraml/upi/v1"
)

// MissionControlUPI is an autogenerated mock type for the MissionControlUPI type
type MissionControlUPI struct {
	mock.Mock
}

// Route provides a mock function with given fields: _a0, _a1
func (_m *MissionControlUPI) Route(_a0 context.Context, _a1 fiber.Request) (*upiv1.PredictValuesResponse, *errors.TuringError) {
	ret := _m.Called(_a0, _a1)

	var r0 *upiv1.PredictValuesResponse
	if rf, ok := ret.Get(0).(func(context.Context, fiber.Request) *upiv1.PredictValuesResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*upiv1.PredictValuesResponse)
		}
	}

	var r1 *errors.TuringError
	if rf, ok := ret.Get(1).(func(context.Context, fiber.Request) *errors.TuringError); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.TuringError)
		}
	}

	return r0, r1
}
