- name: k3s
  k8s_config: {} # populated after running docker-compose setup in infra/docker-compose/dev
    # Example k8s_config to connect to cluster using gke-gcloud-auth-plugin
    # name: dev-cluster
    # cluster:
    #   server: https://k8s.cluster
    #   certificate-authority-data: some_cert_data
    # user:
    #   exec:
    #     apiVersion: client.authentication.k8s.io/v1beta1
    #     args: ["--use_application_default_credentials"]
    #     command: gke-gcloud-auth-plugin
    #     interactiveMode: IfAvailable
    #     provideClusterInfo: true

