name: Fluentd Plugin

on:
  # Automatically run CI on Release and Pre-Release tags and main branch
  # (only if there are changes to relevant paths)
  push:
    tags:
      - "fluentd/v[0-9]+.[0-9]+.[0-9]+*"
    branches:
      - main
    paths:
      - ".github/workflows/fluentd-plugin.yaml"
      - "scripts/fluentd-bigquery/**"

  # To make it possible to trigger e2e CI workflow for any arbitrary git ref
  workflow_dispatch:

jobs:
  release-rules:
    runs-on: ubuntu-latest
    outputs:
      release-type: ${{ steps.release-rules.outputs.release-type }}
    steps:
      - uses: actions/checkout@v4
      - id: release-rules
        uses: ./.github/actions/release-rules
        with:
          prefix: fluentd/

  publish-fluentd:
    # Automatically publish release and pre-release artifacts.
    #
    # As for dev releases, make it possible to publish artifacts
    # manually by approving 'deployment' in the 'manual' environment.
    #
    # Dev build can be released either from the 'main' branch or
    # by running this workflow manually with `workflow_dispatch` event.
    if: >-
      contains('release,pre-release', needs.release-rules.outputs.release-type)
        || ( github.event_name != 'pull_request' )
        || ( github.event.pull_request.head.repo.full_name == github.repository )
    environment: ${{ needs.release-rules.outputs.release-type == 'dev' && 'manual' || '' }}
    runs-on: ubuntu-latest
    outputs:
      fluentd-image: ${{ steps.build-image.outputs.fluentd-image }}
    needs:
      - release-rules
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        id: build-image
        working-directory: scripts/fluentd-bigquery
        env:
          DOCKER_REGISTRY: ghcr.io/${{ github.repository }}
        run: |
          set -o pipefail
          make build-image | tee output.log
          echo "::set-output name=fluentd-image::$(sed -n 's%Building docker image: \(.*\)%\1%p' output.log)"

      - name: Publish Fluentd Plugin Docker Image
        run: docker push ${{ steps.build-image.outputs.fluentd-image }}
