name: sdk

on:
  push:
    paths:
      - ".github/workflows/sdk.yaml"
      - "sdk/**"
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sdk
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: |
            pip-${{ hashFiles('sdk/requirements.txt') }}-${{ hashFiles('sdk/requirements.dev.txt') }}
          restore-keys: pip-

      - name: Install dependencies
        run: make dev

      - name: Run unit tests
        run: make test-unit

  publish:
    if: ${{ startsWith(github.ref, 'refs/tags/sdk/') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sdk
    needs: test
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          # fetch full history for a proper version number assignment
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: |
            pip-${{ hashFiles('sdk/requirements.txt') }}-${{ hashFiles('sdk/requirements.dev.txt') }}
          restore-keys: pip-

      - name: Install dependencies
        run: make dev

      - name: Build
        run: make build

      - name: Publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/*
