// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import (
	client "github.com/gojek/mlp/api/client"
	mock "github.com/stretchr/testify/mock"

	models "github.com/caraml-dev/turing/api/turing/models"

	service "github.com/caraml-dev/turing/api/turing/service"
)

// EnsemblingJobService is an autogenerated mock type for the EnsemblingJobService type
type EnsemblingJobService struct {
	mock.Mock
}

// CreateEnsemblingJob provides a mock function with given fields: job, projectID, ensembler
func (_m *EnsemblingJobService) CreateEnsemblingJob(job *models.EnsemblingJob, projectID models.ID, ensembler *models.PyFuncEnsembler) (*models.EnsemblingJob, error) {
	ret := _m.Called(job, projectID, ensembler)

	var r0 *models.EnsemblingJob
	if rf, ok := ret.Get(0).(func(*models.EnsemblingJob, models.ID, *models.PyFuncEnsembler) *models.EnsemblingJob); ok {
		r0 = rf(job, projectID, ensembler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EnsemblingJob)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.EnsemblingJob, models.ID, *models.PyFuncEnsembler) error); ok {
		r1 = rf(job, projectID, ensembler)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreatePodLabelSelector provides a mock function with given fields: ensemblerName, componentType
func (_m *EnsemblingJobService) CreatePodLabelSelector(ensemblerName string, componentType string) []service.LabelSelector {
	ret := _m.Called(ensemblerName, componentType)

	var r0 []service.LabelSelector
	if rf, ok := ret.Get(0).(func(string, string) []service.LabelSelector); ok {
		r0 = rf(ensemblerName, componentType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.LabelSelector)
		}
	}

	return r0
}

// Delete provides a mock function with given fields: ensemblingJob
func (_m *EnsemblingJobService) Delete(ensemblingJob *models.EnsemblingJob) error {
	ret := _m.Called(ensemblingJob)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.EnsemblingJob) error); ok {
		r0 = rf(ensemblingJob)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: id, options
func (_m *EnsemblingJobService) FindByID(id models.ID, options service.EnsemblingJobFindByIDOptions) (*models.EnsemblingJob, error) {
	ret := _m.Called(id, options)

	var r0 *models.EnsemblingJob
	if rf, ok := ret.Get(0).(func(models.ID, service.EnsemblingJobFindByIDOptions) *models.EnsemblingJob); ok {
		r0 = rf(id, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EnsemblingJob)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.ID, service.EnsemblingJobFindByIDOptions) error); ok {
		r1 = rf(id, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FormatLoggingURL provides a mock function with given fields: ensemblerName, namespace, componentType
func (_m *EnsemblingJobService) FormatLoggingURL(ensemblerName string, namespace string, componentType string) (string, error) {
	ret := _m.Called(ensemblerName, namespace, componentType)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = rf(ensemblerName, namespace, componentType)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(ensemblerName, namespace, componentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDefaultEnvironment provides a mock function with given fields:
func (_m *EnsemblingJobService) GetDefaultEnvironment() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetNamespaceByComponent provides a mock function with given fields: componentType, project
func (_m *EnsemblingJobService) GetNamespaceByComponent(componentType string, project *client.Project) string {
	ret := _m.Called(componentType, project)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, *client.Project) string); ok {
		r0 = rf(componentType, project)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// List provides a mock function with given fields: options
func (_m *EnsemblingJobService) List(options service.EnsemblingJobListOptions) (*service.PaginatedResults, error) {
	ret := _m.Called(options)

	var r0 *service.PaginatedResults
	if rf, ok := ret.Get(0).(func(service.EnsemblingJobListOptions) *service.PaginatedResults); ok {
		r0 = rf(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.PaginatedResults)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(service.EnsemblingJobListOptions) error); ok {
		r1 = rf(options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkEnsemblingJobForTermination provides a mock function with given fields: ensemblingJob
func (_m *EnsemblingJobService) MarkEnsemblingJobForTermination(ensemblingJob *models.EnsemblingJob) error {
	ret := _m.Called(ensemblingJob)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.EnsemblingJob) error); ok {
		r0 = rf(ensemblingJob)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: ensemblingJob
func (_m *EnsemblingJobService) Save(ensemblingJob *models.EnsemblingJob) error {
	ret := _m.Called(ensemblingJob)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.EnsemblingJob) error); ok {
		r0 = rf(ensemblingJob)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
