// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	models "github.com/caraml-dev/turing/api/turing/models"
)

// RoutersRepository is an autogenerated mock type for the RoutersRepository type
type RoutersRepository struct {
	mock.Mock
}

// CountRoutersByCurrentVersionID provides a mock function with given fields: routerVersionID
func (_m *RoutersRepository) CountRoutersByCurrentVersionID(routerVersionID models.ID) int64 {
	ret := _m.Called(routerVersionID)

	var r0 int64
	if rf, ok := ret.Get(0).(func(models.ID) int64); ok {
		r0 = rf(routerVersionID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

type mockConstructorTestingTNewRoutersRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRoutersRepository creates a new instance of RoutersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRoutersRepository(t mockConstructorTestingTNewRoutersRepository) *RoutersRepository {
	mock := &RoutersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
