// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/caraml-dev/turing/api/turing/service"
	mock "github.com/stretchr/testify/mock"

	sync "sync"
)

// uFunc is an autogenerated mock type for the uFunc type
type uFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *uFunc) Execute(_a0 context.Context, _a1 interface{}, _a2 *sync.WaitGroup, _a3 chan<- error, _a4 *service.EventChannel) {
	_m.Called(_a0, _a1, _a2, _a3, _a4)
}

type mockConstructorTestingTnewUFunc interface {
	mock.TestingT
	Cleanup(func())
}

// newUFunc creates a new instance of uFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newUFunc(t mockConstructorTestingTnewUFunc) *uFunc {
	mock := &uFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
